code --install-extension eamodio.gitlens
code --install-extension pkief.material-icon-theme
code --install-extension ms-ceintl.vscode-language-pack-pl
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.python
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension njpwerner.autodocstring
code --install-extension aaron-bond.better-comments
code --install-extension samuelcolvin.jinjahtml
code --install-extension wmaurer.change-case
code --install-extension ms-vscode.powershell
code --install-extension almenon.arepl
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension cardinal90.multi-cursor-case-preserve
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension humao.rest-client
code --install-extension quicktype.quicktype
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension mechatroner.rainbow-csv

